Update `flake8`
This required fixes an error in the config (I also updated the relevant
link, the old one would 404):

    ValueError: Error code '#' supplied to 'extend-ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'

And some errors in the code:

    isort/literal.py:59:8: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
    tests/unit/test_isort.py:13:1: F401 'typing.Dict' imported but unused

The second test conflicted with `mypy`, since `Dict` was only used in
commented annotations, to make them both happy move one of these
annotations out of a comment (in the future we should probably move all
such annotations out of comments)